# shellcheck disable=SC2034,SC2148
# (note - shellcheck directive needs to be at the very top to be effective over the whole file)
# SC2034 - variable appears to be used
# SC2148 - we are shell agnostic

# default.conf file for macOS (Darwin)
#============================
# Do not change variables here!
# To override add yours to the local.conf file which is read after default.conf

#
# use "no" to disable a collection
#
CFG_APPLICATIONS="yes"
CFG_FILESYS="yes"
CFG_HARDWARE="yes"
CFG_KERNEL="yes"
CFG_NETWORK="yes"
CFG_SOFTWARE="yes"
CFG_STINLINE="yes"
CFG_SYSTEM="yes"
CFG_TRACETIME="no"  # show seconds spent in a function

CFG_TEXTWIDTH="74" # set the originally defined, hard-coded, default width of the section headers in lib/html-functions.sh
export COLUMNS=${CFG_TEXTWIDTH}

if [ -z "$OUTDIR" ]
then
  OUTDIR="${VAR_DIR}"
fi

LOCK=/tmp/LockFile-cfg2html

CFG_DATE=""	# used by options [012]
